name: cas12a-m17-md
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - pyyaml
  - pyarrow
  - tqdm
  - mdanalysis
  - mdtraj
  - ambertools
  - pip
  - pip:
      - seaborn

